load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "TelegramApi",
    module_name = "TelegramApi",
    copts = [
        
    ],
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/MolteagramCore"
    ],
    visibility = [
        "//visibility:public",
    ],
)
