load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "PhoneNumberFormat",
    module_name = "PhoneNumberFormat",
    srcs = glob([
		"Sources/**/*.swift",
    ]),
    copts = [
        
    ],
    deps = [
        "//submodules/libphonenumber:libphonenumber",
        "//submodules/AccountContext:AccountContext",
        "//submodules/TelegramCore:TelegramCore",
    ],
    visibility = [
        "//visibility:public",
    ],
)
